/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package yazlab.gui;

import java.awt.Color;
import java.awt.Component;
import yazlab.model.Ingredient;
import yazlab.model.RecipeIngredient;
import yazlab.service.IngredientService;
import yazlab.service.RecipeIngredientService;
import yazlab.service.RecipeService;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.List;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import yazlab.exception.IngredientException;
import yazlab.exception.RecipeException;
import yazlab.exception.RecipeIngredientException;
import yazlab.model.Category;
import yazlab.model.Recipe;
import yazlab.model.Unit;
import yazlab.request.FilterRequest;
import yazlab.request.RecipeAddingRequest;
import yazlab.request.RecipeIngredientAddingRequest;
import yazlab.request.RecipeIngredientAddingRequestGui;
import yazlab.service.UnitAndPriceConversation;

/**
 *
 * @author kaan
 */
public class RecipeFrame extends javax.swing.JFrame {

    private RecipeService recipeService;
    private RecipeIngredientService recipeIngredientService;
    private IngredientService ingredientService;
    private boolean addRecipeButtonClicked;
    private boolean showButtonClicked;
    private boolean removeRecipeButtonClicked;
    private boolean updateRecipeButtonClicked;
    private Long recipeIdToBeUpdated;

    /**
     * Creates new form NewJFrame
     */
    public RecipeFrame() {
        initComponents();
        recipeService = RecipeService.getInstance();
        recipeIngredientService = RecipeIngredientService.getInstance();
        ingredientService = IngredientService.getInstance();
        addUnitTypeAddCb = new JComboBox<>(Unit.values());
        addAddingCategoryCb = new JComboBox<>(Category.values());
        addRecipeButtonClicked = false;
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        jLabel15.setVisible(false);
        jLabel16.setVisible(false);
        jLabel17.setVisible(false);
        jLabel18.setVisible(false);
        addNameTf.setVisible(false);
        addPreparationTimeTf.setVisible(false);
        addIngredientAmountAddTf.setVisible(false);
        addAddingCategoryCb.setVisible(false);
        addUnitTypeAddCb.setVisible(false);
        addIngredientAddingCb.setVisible(false);
        addAddIngredientButton.setVisible(false);
        addRemoveIngredientButton.setVisible(false);
        addRemoveIngredientCb.setVisible(false);
        addExplanationTf.setVisible(false);
        addButton.setVisible(false);
        showButtonClicked = false;
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel6.setVisible(false);
        nameTf.setVisible(false);
        maxPriceTf.setVisible(false);
        maxIngredientAmountTf.setVisible(false);
        maxPreparationTimeTf.setVisible(false);
        categoryFilter.setVisible(false);
        filterButton.setVisible(false);
        sortByPriceFilterButton.setVisible(false);
        sortByPreparationTimeButton.setVisible(false);
        sortByIngredientAmountButton.setVisible(false);
        recipeList.setVisible(false);
        recipeTextArea.setVisible(false);
        removeRecipeButtonClicked = false;
        jLabel11.setVisible(false);
        removeRecipeTf.setVisible(false);
        removeButton.setVisible(false);
        updateRecipeButtonClicked = false;
        jLabel5.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        jLabel10.setVisible(false);
        jLabel19.setVisible(false);
        jLabel20.setVisible(false);
        updateNameTf.setVisible(false);
        updatePreparationTimeTf.setVisible(false);
        updateRemoveIngredientCb.setVisible(false);
        updateRemoveIngredientButton.setVisible(false);
        updateChangeCategoryCb.setVisible(false);
        updateIngredientAddingCb.setVisible(false);
        updateUnitTypeAddCb.setVisible(false);
        updateIngredientAmountAddTf.setVisible(false);
        updateAddIngredientButton.setVisible(false);
        updateButton.setVisible(false);
        updateInstructionTf.setVisible(false);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        recipeAddingButton = new javax.swing.JButton();
        recipeRemovingButton = new javax.swing.JButton();
        updateRecipeButton = new javax.swing.JButton();
        showRecipeButton = new javax.swing.JButton();
        filterButton = new javax.swing.JButton();
        sortByPreparationTimeButton = new javax.swing.JButton();
        sortByIngredientAmountButton = new javax.swing.JButton();
        sortByPriceFilterButton = new javax.swing.JButton();
        recipeList = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        recipeTextArea = new javax.swing.JTextArea();
        nameTf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        maxPriceTf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        maxIngredientAmountTf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        maxPreparationTimeTf = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        categoryFilter = new javax.swing.JComboBox<>(Category.getNames());
        jLabel6 = new javax.swing.JLabel();
        updateNameTf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        updatePreparationTimeTf = new javax.swing.JTextField();
        updateIngredientAddingCb = new javax.swing.JComboBox<>();
        updateAddIngredientButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        updateUnitTypeAddCb = new javax.swing.JComboBox<>(Unit.values());
        jLabel9 = new javax.swing.JLabel();
        updateIngredientAmountAddTf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        updateRemoveIngredientCb = new javax.swing.JComboBox<>();
        updateRemoveIngredientButton = new javax.swing.JButton();
        updateChangeCategoryCb = new javax.swing.JComboBox<>(Category.getNames());
        jLabel11 = new javax.swing.JLabel();
        removeRecipeTf = new javax.swing.JTextField();
        removeButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        addIngredientAddingCb = new javax.swing.JComboBox<>();
        addUnitTypeAddCb = new javax.swing.JComboBox<>(Unit.values());
        addIngredientAmountAddTf = new javax.swing.JTextField();
        addRemoveIngredientButton = new javax.swing.JButton();
        addRemoveIngredientCb = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        addNameTf = new javax.swing.JTextField();
        addPreparationTimeTf = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        addAddIngredientButton = new javax.swing.JButton();
        addExplanationTf = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        updateInstructionTf = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        addAddingCategoryCb = new javax.swing.JComboBox<>(Category.values());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        recipeAddingButton.setText("Add Recipe");
        recipeAddingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recipeAddingButtonActionPerformed(evt);
            }
        });

        recipeRemovingButton.setText("Remove Recipe");
        recipeRemovingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recipeRemovingButtonActionPerformed(evt);
            }
        });

        updateRecipeButton.setText("Update Recipe");
        updateRecipeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateRecipeButtonActionPerformed(evt);
            }
        });

        showRecipeButton.setText("Show Recipes");
        showRecipeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showRecipeButtonActionPerformed(evt);
            }
        });

        filterButton.setText("Filter");
        filterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterButtonActionPerformed(evt);
            }
        });

        sortByPreparationTimeButton.setText("Sort By Preparation Time");
        sortByPreparationTimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortByPreparationTimeButtonActionPerformed(evt);
            }
        });

        sortByIngredientAmountButton.setText("Sort By Ingredient Amount");
        sortByIngredientAmountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortByIngredientAmountButtonActionPerformed(evt);
            }
        });

        sortByPriceFilterButton.setText("Sort By Price");
        sortByPriceFilterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortByPriceFilterButtonActionPerformed(evt);
            }
        });

        recipeList.setModel(new javax.swing.DefaultComboBoxModel<>());
        recipeList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                recipeListItemStateChanged(evt);
            }
        });
        recipeList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recipeListActionPerformed(evt);
            }
        });

        recipeTextArea.setColumns(20);
        recipeTextArea.setRows(5);
        jScrollPane1.setViewportView(recipeTextArea);

        jLabel1.setText("Name");

        jLabel2.setText("Max Price");

        jLabel3.setText("Max Ingredient Amount");

        jLabel4.setText("Max Preparation Time");

        maxPreparationTimeTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxPreparationTimeTfActionPerformed(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Name");

        categoryFilter.addItem("All");
        categoryFilter.setModel(new javax.swing.DefaultComboBoxModel<>());
        categoryFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryFilterActionPerformed(evt);
            }
        });

        jLabel6.setText("Category");

        jLabel7.setText("Preparation Time");

        updateIngredientAddingCb.setModel(new javax.swing.DefaultComboBoxModel<>());

        updateAddIngredientButton.setText("Add Ingredient");
        updateAddIngredientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateAddIngredientButtonActionPerformed(evt);
            }
        });

        jLabel8.setText("Add Ingredient");

        jLabel9.setText("Unit Type");

        updateIngredientAmountAddTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateIngredientAmountAddTfActionPerformed(evt);
            }
        });

        jLabel10.setText("Ingredient Amount");

        updateRemoveIngredientButton.setText("Remove Ingredient");
        updateRemoveIngredientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateRemoveIngredientButtonActionPerformed(evt);
            }
        });

        updateChangeCategoryCb.setModel(new javax.swing.DefaultComboBoxModel<>());

        jLabel11.setText("Name");

        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        jLabel12.setText("Name");

        jLabel13.setText("Preparation Time");

        jLabel14.setText("Ingredient");

        jLabel15.setText("Unit Type");

        jLabel16.setText("Ingredient Amount");

        addIngredientAddingCb.setModel(new javax.swing.DefaultComboBoxModel<>());

        addUnitTypeAddCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUnitTypeAddCbActionPerformed(evt);
            }
        });

        addRemoveIngredientButton.setText("Remove Ingredient");
        addRemoveIngredientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRemoveIngredientButtonActionPerformed(evt);
            }
        });

        addRemoveIngredientCb.setModel(new javax.swing.DefaultComboBoxModel<>());

        jLabel17.setText("Category");

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        addAddIngredientButton.setText("Add Ingredient");
        addAddIngredientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAddIngredientButtonActionPerformed(evt);
            }
        });

        addExplanationTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addExplanationTfActionPerformed(evt);
            }
        });

        jLabel18.setText("Explanation");

        jLabel19.setText("Instruction");

        jLabel20.setText("Category");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(sortByPriceFilterButton)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(recipeRemovingButton)
                                    .addComponent(sortByPreparationTimeButton)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel12)
                                                        .addGap(58, 58, 58)
                                                        .addComponent(addNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel13)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(addPreparationTimeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(28, 28, 28)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel17)
                                                    .addComponent(addAddingCategoryCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(addIngredientAddingCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel14))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(33, 33, 33)
                                                        .addComponent(jLabel15)
                                                        .addGap(55, 55, 55))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(addUnitTypeAddCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(32, 32, 32)))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel16)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(8, 8, 8)
                                                        .addComponent(addIngredientAmountAddTf, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(addRemoveIngredientButton)
                                                .addGap(24, 24, 24)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(145, 145, 145)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(removeButton)
                                                    .addComponent(removeRecipeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(165, 165, 165)
                                                .addComponent(jLabel11))))
                                    .addComponent(recipeAddingButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(110, 110, 110)
                                .addComponent(addExplanationTf, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(recipeList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(addAddIngredientButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(addRemoveIngredientCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(addButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(showRecipeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addComponent(jLabel6)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(categoryFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(maxPreparationTimeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(updateRecipeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(61, 61, 61))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(maxIngredientAmountTf, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jLabel8)
                                                            .addComponent(updateIngredientAddingCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(69, 69, 69))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(71, 71, 71)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel5)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(updateNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                        .addComponent(jLabel7)
                                                                        .addGap(12, 12, 12))
                                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                        .addComponent(jLabel19)
                                                                        .addGap(57, 57, 57)))
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                    .addComponent(updatePreparationTimeTf, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                                                    .addComponent(updateInstructionTf))))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(updateUnitTypeAddCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel9))
                                                .addGap(75, 75, 75)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(updateIngredientAmountAddTf, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(jLabel10)
                                                            .addGap(0, 11, Short.MAX_VALUE)))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(updateRemoveIngredientCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(updateChangeCategoryCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(updateRemoveIngredientButton)
                                            .addComponent(jLabel20)
                                            .addComponent(updateAddIngredientButton, javax.swing.GroupLayout.Alignment.TRAILING)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(maxPriceTf, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jLabel1)
                                        .addGap(66, 66, 66)
                                        .addComponent(nameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(88, 88, 88)
                                .addComponent(updateButton))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sortByIngredientAmountButton)
                        .addGap(227, 227, 227)
                        .addComponent(filterButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(addPreparationTimeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel16)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(addIngredientAmountAddTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(addUnitTypeAddCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(addIngredientAddingCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addAddIngredientButton)
                            .addComponent(updateAddIngredientButton)
                            .addComponent(updateIngredientAmountAddTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateUnitTypeAddCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateIngredientAddingCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(addAddingCategoryCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(recipeAddingButton)
                                            .addComponent(updateRecipeButton)
                                            .addComponent(recipeRemovingButton)
                                            .addComponent(showRecipeButton))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(updateRemoveIngredientCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(updateRemoveIngredientButton)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(37, 37, 37)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel12)
                                                    .addComponent(addNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(updateNameTf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7)
                                            .addComponent(updatePreparationTimeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(updateChangeCategoryCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel20)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(removeRecipeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(updateInstructionTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addComponent(removeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(60, 60, 60)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(addRemoveIngredientCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addRemoveIngredientButton))
                                .addGap(60, 60, 60)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(maxPriceTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(maxIngredientAmountTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(maxPreparationTimeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(categoryFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(29, 29, 29))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addButton)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(87, 87, 87)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(88, 88, 88)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(recipeList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel18)
                                        .addComponent(addExplanationTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(updateButton))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sortByPreparationTimeButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(filterButton)
                        .addComponent(sortByPriceFilterButton)
                        .addComponent(sortByIngredientAmountButton)))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 373, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterButtonActionPerformed
        String name = nameTf.getText();
        try {
            String maxPriceString = maxPriceTf.getText();
            String maxPreparationTimeString = maxPreparationTimeTf.getText();
            String maxIngredientAmountString = maxIngredientAmountTf.getText();
            Integer maxPreparationTime = null;
            Integer maxIngredientAmount = null;
            Float maxPrice = null;

            if (maxPriceString.isBlank() || maxPriceString.isEmpty()) {
                maxPrice = -1F;
            } else {
                maxPrice = Float.parseFloat(maxPriceString);
            }

            if (maxPreparationTimeString.isBlank() || maxPreparationTimeString.isEmpty()) {
                maxPreparationTime = -1;
            } else {
                maxPreparationTime = Integer.parseInt(maxPreparationTimeString);
            }
            if (maxIngredientAmountString.isBlank() || maxIngredientAmountString.isEmpty()) {
                maxIngredientAmount = -1;
            } else {
                maxIngredientAmount = Integer.parseInt(maxIngredientAmountString);
            }
            String categoryName = (String) categoryFilter.getSelectedItem();
            List<Recipe> filteredRecipes = recipeService.filter(new FilterRequest(name, maxPreparationTime, categoryName, maxPrice, maxIngredientAmount));
            recipeList.removeAllItems();
            for (Recipe recipe : filteredRecipes) {
                recipeList.addItem(recipe);
            }
        } catch (NumberFormatException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_filterButtonActionPerformed

    private void maxPreparationTimeTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxPreparationTimeTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxPreparationTimeTfActionPerformed

    private void categoryFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryFilterActionPerformed

    private void updateIngredientAmountAddTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateIngredientAmountAddTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateIngredientAmountAddTfActionPerformed

    private void recipeAddingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recipeAddingButtonActionPerformed
        if (!addRecipeButtonClicked) {
            jLabel12.setVisible(true);
            jLabel13.setVisible(true);
            jLabel14.setVisible(true);
            jLabel15.setVisible(true);
            jLabel16.setVisible(true);
            jLabel17.setVisible(true);
            jLabel18.setVisible(true);
            addNameTf.setVisible(true);
            addPreparationTimeTf.setVisible(true);
            addIngredientAmountAddTf.setVisible(true);
            addAddingCategoryCb.setVisible(true);
            addUnitTypeAddCb.setVisible(true);
            addIngredientAddingCb.setVisible(true);
            addAddIngredientButton.setVisible(true);
            addRemoveIngredientButton.setVisible(true);
            addRemoveIngredientCb.setVisible(true);
            addExplanationTf.setVisible(true);
            addButton.setVisible(true);
            addUnitTypeAddCb.removeAllItems();
            for (Unit unit : Unit.values()) {
                addUnitTypeAddCb.addItem(unit);
            }
            try {
                for (Ingredient ingredient : ingredientService.getAll()) {
                    addIngredientAddingCb.addItem(ingredient.getName());
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
            addRecipeButtonClicked = true;
        } else {
            jLabel12.setVisible(false);
            jLabel13.setVisible(false);
            jLabel14.setVisible(false);
            jLabel15.setVisible(false);
            jLabel16.setVisible(false);
            jLabel17.setVisible(false);
            jLabel18.setVisible(false);
            addNameTf.setVisible(false);
            addPreparationTimeTf.setVisible(false);
            addIngredientAmountAddTf.setVisible(false);
            addAddingCategoryCb.setVisible(false);
            addUnitTypeAddCb.setVisible(false);
            addIngredientAddingCb.setVisible(false);
            addAddIngredientButton.setVisible(false);
            addRemoveIngredientButton.setVisible(false);
            addRemoveIngredientCb.setVisible(false);
            addExplanationTf.setVisible(false);
            addButton.setVisible(false);
            addRecipeButtonClicked = false;
        }
    }//GEN-LAST:event_recipeAddingButtonActionPerformed

    private void addAddIngredientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAddIngredientButtonActionPerformed
        String ingredientName = (String) addIngredientAddingCb.getSelectedItem();
        try {
            Ingredient ingredient = ingredientService.getByName(ingredientName);
            Unit unit = (Unit) addUnitTypeAddCb.getSelectedItem();
            Float usingAmount = Float.parseFloat(addIngredientAmountAddTf.getText());
            RecipeIngredient recipeIngredientWithoutId
                    = recipeIngredientService.createRecipeIngredientForGui(new RecipeIngredientAddingRequestGui(ingredient.getId(), unit, usingAmount));
            addRemoveIngredientCb.addItem(recipeIngredientWithoutId);
            addIngredientAddingCb.removeItem(ingredientName);
        } catch (SQLException | NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_addAddIngredientButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        String name = addNameTf.getText();
        Category category = (Category) addAddingCategoryCb.getSelectedItem();
        try {
            Integer preparationTime = Integer.parseInt(addPreparationTimeTf.getText());
            String explanation = addExplanationTf.getText();
            recipeService.addRecipe(new RecipeAddingRequest(name, category, preparationTime, explanation));
            int size = addRemoveIngredientCb.getItemCount();
            for (int i = 0; i < size; i++) {
                RecipeIngredient recipeIngredient = addRemoveIngredientCb.getItemAt(i);
                recipeIngredientService.create(new RecipeIngredientAddingRequest(name, recipeIngredient.toString(), recipeIngredient.getUsingAmount(), recipeIngredient.getUnit()));
            }
            JOptionPane.showMessageDialog(null, "Successful");
        } catch (SQLException | RecipeIngredientException | RecipeException | IngredientException | NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void addRemoveIngredientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRemoveIngredientButtonActionPerformed
        RecipeIngredient recipeIngredient = (RecipeIngredient) addRemoveIngredientCb.getSelectedItem();
        String ingredientName = null;
        try {
            ingredientName = ingredientService.getById(recipeIngredient.getIngredientId()).getName();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        addIngredientAddingCb.addItem(ingredientName);
        addRemoveIngredientCb.removeItemAt(addRemoveIngredientCb.getSelectedIndex());
    }//GEN-LAST:event_addRemoveIngredientButtonActionPerformed

    private void addExplanationTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addExplanationTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addExplanationTfActionPerformed

    private void addUnitTypeAddCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUnitTypeAddCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addUnitTypeAddCbActionPerformed

    private void showRecipeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showRecipeButtonActionPerformed
        if (!showButtonClicked) {
            try {
                for (Recipe recipe : recipeService.getAll()) {
                    recipeList.addItem(recipe);
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
            for (String categoryName : Category.getNames()) {
                categoryFilter.addItem(categoryName);
            }
            categoryFilter.addItem("All");
            showButtonClicked = true;
            jLabel1.setVisible(true);
            jLabel2.setVisible(true);
            jLabel3.setVisible(true);
            jLabel4.setVisible(true);
            jLabel6.setVisible(true);
            nameTf.setVisible(true);
            maxPriceTf.setVisible(true);
            maxIngredientAmountTf.setVisible(true);
            maxPreparationTimeTf.setVisible(true);
            categoryFilter.setVisible(true);
            filterButton.setVisible(true);
            sortByPriceFilterButton.setVisible(true);
            sortByPreparationTimeButton.setVisible(true);
            sortByIngredientAmountButton.setVisible(true);
            recipeList.setVisible(true);
            recipeTextArea.setVisible(true);
        } else {
            showButtonClicked = false;
            jLabel1.setVisible(false);
            jLabel2.setVisible(false);
            jLabel3.setVisible(false);
            jLabel4.setVisible(false);
            jLabel6.setVisible(false);
            nameTf.setVisible(false);
            maxPriceTf.setVisible(false);
            maxIngredientAmountTf.setVisible(false);
            maxPreparationTimeTf.setVisible(false);
            categoryFilter.setVisible(false);
            filterButton.setVisible(false);
            sortByPriceFilterButton.setVisible(false);
            sortByPreparationTimeButton.setVisible(false);
            sortByIngredientAmountButton.setVisible(false);
            recipeList.setVisible(false);
            recipeTextArea.setVisible(false);
        }
    }//GEN-LAST:event_showRecipeButtonActionPerformed

    private void recipeRemovingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recipeRemovingButtonActionPerformed
        if (!removeRecipeButtonClicked) {
            removeRecipeButtonClicked = true;
            jLabel11.setVisible(true);
            removeRecipeTf.setVisible(true);
            removeButton.setVisible(true);
        } else {
            removeRecipeButtonClicked = false;
            jLabel11.setVisible(false);
            removeRecipeTf.setVisible(false);
            removeButton.setVisible(false);
        }
    }//GEN-LAST:event_recipeRemovingButtonActionPerformed

    private void updateRecipeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateRecipeButtonActionPerformed
        if (!updateRecipeButtonClicked) {
            String recipeName = JOptionPane.showInputDialog("Please Enter Recipe Name");
            if (recipeName.isEmpty() || recipeName.isBlank()) {
                JOptionPane.showMessageDialog(null, "Invalid Name");
                return;
            }
            try {
                if (!recipeService.isInDatabaseByName(recipeName)) {
                    JOptionPane.showMessageDialog(null, "Invalid Recipe Name");
                    return;
                }
                Recipe recipe = recipeService.getByName(recipeName);
                recipeIdToBeUpdated = recipe.getId();
                updateNameTf.setText(recipeName);
                updatePreparationTimeTf.setText(String.valueOf(recipe.getPreperationTimeInMinute()));
                updateInstructionTf.setText(recipe.getInstructions());
                List<RecipeIngredient> recipeIngredients = recipeIngredientService.getByRecipeId(recipe.getId());
                updateRemoveIngredientCb.removeAllItems();
                for (RecipeIngredient recipeIngredient : recipeIngredients) {
                    updateRemoveIngredientCb.addItem(recipeIngredient);
                }
                for (Category category : Category.values()) {
                    updateChangeCategoryCb.addItem(category.name());
                }
                updateChangeCategoryCb.setSelectedItem(recipe.getCategory().name());
                updateIngredientAddingCb.removeAllItems();
                for (Ingredient ingredient : ingredientService.getAll()) {
                    boolean isInRemovingList = false;
                    for (int i = 0; i < updateRemoveIngredientCb.getItemCount(); i++) {
                        RecipeIngredient recipeIngredient = updateRemoveIngredientCb.getItemAt(i);
                        if (ingredient.getId().longValue() == recipeIngredient.getIngredientId().longValue()) {
                            isInRemovingList = true;
                            break;
                        }
                    }
                    if (!isInRemovingList) {
                        updateIngredientAddingCb.addItem(ingredient);
                    }
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
            updateRecipeButtonClicked = true;
            jLabel5.setVisible(true);
            jLabel7.setVisible(true);
            jLabel8.setVisible(true);
            jLabel9.setVisible(true);
            jLabel10.setVisible(true);
            jLabel19.setVisible(true);
            jLabel20.setVisible(true);
            updateNameTf.setVisible(true);
            updatePreparationTimeTf.setVisible(true);
            updateRemoveIngredientCb.setVisible(true);
            updateRemoveIngredientButton.setVisible(true);
            updateChangeCategoryCb.setVisible(true);
            updateIngredientAddingCb.setVisible(true);
            updateUnitTypeAddCb.setVisible(true);
            updateIngredientAmountAddTf.setVisible(true);
            updateAddIngredientButton.setVisible(true);
            updateButton.setVisible(true);
            updateInstructionTf.setVisible(true);
        } else {
            updateRecipeButtonClicked = false;
            jLabel5.setVisible(false);
            jLabel7.setVisible(false);
            jLabel8.setVisible(false);
            jLabel9.setVisible(false);
            jLabel10.setVisible(false);
            jLabel19.setVisible(false);
            jLabel20.setVisible(false);
            updateNameTf.setVisible(false);
            updatePreparationTimeTf.setVisible(false);
            updateRemoveIngredientCb.setVisible(false);
            updateRemoveIngredientButton.setVisible(false);
            updateChangeCategoryCb.setVisible(false);
            updateIngredientAddingCb.setVisible(false);
            updateUnitTypeAddCb.setVisible(false);
            updateIngredientAmountAddTf.setVisible(false);
            updateAddIngredientButton.setVisible(false);
            updateButton.setVisible(false);
            updateInstructionTf.setVisible(false);
        }
    }//GEN-LAST:event_updateRecipeButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        String categoryName = (String) updateChangeCategoryCb.getSelectedItem();
        try {
            RecipeAddingRequest recipeAddingRequest = new RecipeAddingRequest(updateNameTf.getText(), Category.valueOf(categoryName), Integer.parseInt(updatePreparationTimeTf.getText()), updateInstructionTf.getText());
            recipeService.updateRecipe(recipeAddingRequest, recipeIdToBeUpdated);
            JOptionPane.showMessageDialog(null, "Successful");
        } catch (SQLException | NumberFormatException | RecipeException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        String recipeName = removeRecipeTf.getText();
        try {
            recipeService.deleteRecipeByName(recipeName);
            JOptionPane.showMessageDialog(null, "Successful");

        } catch (SQLException | RecipeException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_removeButtonActionPerformed

    private void recipeListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_recipeListItemStateChanged
        recipeTextArea.setText("");
        String infoMessage = null;
        try {
            Recipe selectedRecipe = (Recipe) recipeList.getSelectedItem();
            if (selectedRecipe == null) {
                return;
            }
            StringBuilder sb = new StringBuilder();
            sb.append("Name : ").append(selectedRecipe.getName()).append("\n").append("Preparation Time (In Minute) : ").append(selectedRecipe.getPreperationTimeInMinute())
                    .append("\n").append("Instruction : ").append(selectedRecipe.getInstructions()).append("\n")
                    .append("Category : ").append(selectedRecipe.getCategory().name()).append("\n")
                    .append("Total Price : ").append(recipeService.getTotalPriceOfRecipe(selectedRecipe))
                    .append("\n");
            for (RecipeIngredient recipeIngredient : recipeIngredientService.getByRecipeId(selectedRecipe.getId())) {
                Ingredient ingredient = ingredientService.getById(recipeIngredient.getIngredientId());
                sb.append("Ingredient Name : ").append(ingredient.getName())
                        .append("\n").append("Using Amount : ").append(recipeIngredient.getUsingAmount())
                        .append("\n").append("Using Unit : ").append(recipeIngredient.getUnit().name())
                        .append("\n").append("Price : ").append(UnitAndPriceConversation.calculatePrice(ingredient.getUnit(), ingredient.getUnitPrice(), recipeIngredient.getUnit(), recipeIngredient.getUsingAmount()))
                        .append("\n");
                if (!UnitAndPriceConversation.isSufficentUsingAmount(ingredient.getUnit(), ingredient.getAmount(), recipeIngredient.getUnit(), recipeIngredient.getUsingAmount())) {
                    sb.append("There is less in the warehouse than the specified amount").append("\n");
                    recipeList.setRenderer(new DefaultListCellRenderer() {

                        @Override
                        public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                            Component component = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                            if (selectedRecipe.equals(value)) {
                                component.setForeground(Color.RED); 
                            }
                            else {
                                component.setForeground(Color.BLACK); 
                            }
                            return component ;
                        }

                    });
                }
            }
            infoMessage = sb.toString();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        recipeTextArea.setText(infoMessage);
    }//GEN-LAST:event_recipeListItemStateChanged

    private void recipeListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recipeListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recipeListActionPerformed

    private void updateAddIngredientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateAddIngredientButtonActionPerformed
        Ingredient ingredient = (Ingredient) updateIngredientAddingCb.getSelectedItem();
        Unit unit = (Unit) updateUnitTypeAddCb.getSelectedItem();
        String ingredientAmountString = updateIngredientAmountAddTf.getText();
        try {
            Recipe recipe = recipeService.getById(recipeIdToBeUpdated);
            Float ingredientAmount = Float.parseFloat(ingredientAmountString);
            RecipeIngredientAddingRequest recipeIngredientAddingRequest = new RecipeIngredientAddingRequest(recipe.getName(), ingredient.getName(), ingredientAmount, unit);
            recipeIngredientService.create(recipeIngredientAddingRequest);
            RecipeIngredient recipeIngredient = recipeIngredientService.getByRecipeIdAndIngredientId(recipe.getId(), ingredient.getId());
            updateIngredientAddingCb.removeItem(ingredient);
            updateRemoveIngredientCb.addItem(recipeIngredient);
        } catch (SQLException | NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_updateAddIngredientButtonActionPerformed

    private void updateRemoveIngredientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateRemoveIngredientButtonActionPerformed
        RecipeIngredient recipeIngredientToRemove = (RecipeIngredient) updateRemoveIngredientCb.getSelectedItem();
        try {
            recipeIngredientService.deleteByRecipeIdAndIngredientId(recipeIngredientToRemove.getRecipeId(), recipeIngredientToRemove.getIngredientId());
            Ingredient ingredient = ingredientService.getById(recipeIngredientToRemove.getIngredientId());
            updateIngredientAddingCb.addItem(ingredient);
            updateRemoveIngredientCb.removeItem(recipeIngredientToRemove);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_updateRemoveIngredientButtonActionPerformed

    private void sortByPriceFilterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortByPriceFilterButtonActionPerformed
        List<String> notOrderedRecipes = new LinkedList();
        for (int i = 0; i < recipeList.getItemCount(); i++) {
            notOrderedRecipes.add(recipeList.getItemAt(i).getName());
        }
        try {
            List<Recipe> orderedRecipes = recipeService.getRecipesByPriceOrdered(notOrderedRecipes);
            recipeList.removeAllItems();
            for (Recipe recipe : orderedRecipes) {
                recipeList.addItem(recipe);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_sortByPriceFilterButtonActionPerformed

    private void sortByPreparationTimeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortByPreparationTimeButtonActionPerformed
        List<String> notOrderedRecipes = new LinkedList();
        for (int i = 0; i < recipeList.getItemCount(); i++) {
            notOrderedRecipes.add(recipeList.getItemAt(i).getName());
        }
        try {
            List<Recipe> orderedRecipes = recipeService.getRecipesByPreparationTimeOrdered(notOrderedRecipes);
            recipeList.removeAllItems();
            for (Recipe recipe : orderedRecipes) {
                recipeList.addItem(recipe);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_sortByPreparationTimeButtonActionPerformed

    private void sortByIngredientAmountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortByIngredientAmountButtonActionPerformed
        List<String> notOrderedRecipes = new LinkedList();
        for (int i = 0; i < recipeList.getItemCount(); i++) {
            notOrderedRecipes.add(recipeList.getItemAt(i).getName());
        }
        try {
            List<Recipe> orderedRecipes = recipeService.getRecipesByIngredientAmountOrdered(notOrderedRecipes);
            recipeList.removeAllItems();
            for (Recipe recipe : orderedRecipes) {
                recipeList.addItem(recipe);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_sortByIngredientAmountButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecipeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecipeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecipeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecipeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecipeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAddIngredientButton;
    private javax.swing.JComboBox<Category> addAddingCategoryCb;
    private javax.swing.JButton addButton;
    private javax.swing.JTextField addExplanationTf;
    private javax.swing.JComboBox<String> addIngredientAddingCb;
    private javax.swing.JTextField addIngredientAmountAddTf;
    private javax.swing.JTextField addNameTf;
    private javax.swing.JTextField addPreparationTimeTf;
    private javax.swing.JButton addRemoveIngredientButton;
    private javax.swing.JComboBox<RecipeIngredient> addRemoveIngredientCb;
    private javax.swing.JComboBox<Unit> addUnitTypeAddCb;
    private javax.swing.JComboBox<String> categoryFilter;
    private javax.swing.JButton filterButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField maxIngredientAmountTf;
    private javax.swing.JTextField maxPreparationTimeTf;
    private javax.swing.JTextField maxPriceTf;
    private javax.swing.JTextField nameTf;
    private javax.swing.JButton recipeAddingButton;
    private javax.swing.JComboBox<Recipe> recipeList;
    private javax.swing.JButton recipeRemovingButton;
    private javax.swing.JTextArea recipeTextArea;
    private javax.swing.JButton removeButton;
    private javax.swing.JTextField removeRecipeTf;
    private javax.swing.JButton showRecipeButton;
    private javax.swing.JButton sortByIngredientAmountButton;
    private javax.swing.JButton sortByPreparationTimeButton;
    private javax.swing.JButton sortByPriceFilterButton;
    private javax.swing.JButton updateAddIngredientButton;
    private javax.swing.JButton updateButton;
    private javax.swing.JComboBox<String> updateChangeCategoryCb;
    private javax.swing.JComboBox<Ingredient> updateIngredientAddingCb;
    private javax.swing.JTextField updateIngredientAmountAddTf;
    private javax.swing.JTextField updateInstructionTf;
    private javax.swing.JTextField updateNameTf;
    private javax.swing.JTextField updatePreparationTimeTf;
    private javax.swing.JButton updateRecipeButton;
    private javax.swing.JButton updateRemoveIngredientButton;
    private javax.swing.JComboBox<RecipeIngredient> updateRemoveIngredientCb;
    private javax.swing.JComboBox<Unit> updateUnitTypeAddCb;
    // End of variables declaration//GEN-END:variables
}
